version: '2'

services:
  web:
    container_name: abdullah_code_challenge
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/usr/share/nginx/html/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    container_name: abdullah_code_challenge_php
    image: php:fpm
    volumes:
      - ./code:/usr/share/nginx/html/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
