#!/bin/bash

docker rm -f abdullah_code_challenge abdullah_code_challenge_php > /dev/null 2>&1
docker-compose up -d
IPADDR="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' abdullah_code_challenge)"
echo "Please hit: ${IPADDR}"